name: Test and Deploy to Cafe24

on:
  push:
    branches: [ "main" ] # 메인 브랜치에 푸시될 때 실행

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. PHP 및 Composer 세팅
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # 카페24 서버 버전과 맞추는 것이 좋습니다.
          extensions: mbstring, xml, ctype, iconv, mysql

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # 2. PHPUnit 테스트 실행
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit tests

      - name: Re-install for Production
        # 배포 직전에 dev 라이브러리(PHPUnit 등)를 제거하고 최적화
        run: composer install --no-dev --optimize-autoloader

      - name: 🚚 Deploy src to www
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: false
          local-dir: src/
          server-dir: /src/

      # 두 번째 폴더 배포
      - name: 🚚 Deploy assets to www
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: false
          local-dir: www/
          server-dir: /www/

      - name: 🚚 Deploy assets to vendor
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: vendor/
          server-dir: /vendor/

      - name: 🚚 Deploy assets to fragments
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: false
          local-dir: fragments/
          server-dir: /fragments/

      - name: Execute DB Migration via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ./vendor/bin/doctrine-migrations migrate